---
title: "5_modelisation"
author: "Psqrt"
date: "16/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages et fonctions externes

```{r, message=F, warning=F}
source("./0_packages.R")
```

```{r}
type_col = readRDS("./../data/type_col.rds")
train = data.table::fread(file = "./../data/train.csv", colClasses = type_col) %>% as.data.frame()
test = data.table::fread(file = "./../data/test.csv", colClasses = type_col) %>% as.data.frame()
```


```{r}
set.seed(1234)

train_smote <- SMOTE(target ~ .-id, train, perc.over = 100, perc.under=200)
table(train_smote$target)

n<-table(train$target)[1]/table(train$target)[2]
train_weight <- train %>% mutate(weight = if_else(target==1,n,1))
train_weight %>% group_by(target) %>% summarise(n=sum(weight))

df<- train %>% filter(target=="no")
n_1<-table(train$target)[2]
sampling<-sample(df$id,n_1,replace = F)
df_0<- train %>% filter(id %in% sampling)
df_1<- train %>% filter(target=="yes")
train_down <- rbind.data.frame(df_0,df_1)
table(train_down$target)
```


## Exportation

```{r}
save(train, test, train_smote, train_weight, train_down,
     file = "./../data/bases_pour_modelisation.RData")
```

