---
title: "03_traitement"
author: "Psqrt"
date: "16/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages et fonctions externes

```{r, message=F, warning=F}
source("./0_packages.R")
```

```{r}
type_col = readRDS("./../data/data_sel_type_col.rds")
data_sel = data.table::fread(file = "./../data/data_sel.csv", colClasses = type_col) %>% as.data.frame()
```

## AFDM

```{r}
library("FactoMineR") 
library("factoextra")
```

```{r}
df<- data_sel %>% filter(dataset=="train")
res_famd <- FAMD(df[-c(1:3)], graph = FALSE)
saveRDS(object = res_famd,
      file = "./../data/res_famd.rds")
```

```{r}
res_famd<-readRDS("./../data/res_famd.rds")
```


```{r}
library(glue)
library(ggrepel)
```

```{r}
coord<-res_famd$quali.var$coord %>% as.data.frame()
liste_var_factor = type_col[type_col == "factor"]
liste_var_factor<-names(liste_var_factor[-1])
name<-c()

for (var in liste_var_factor) {
    df<-data_sel %>% filter(dataset=="train") %>% select(var) 
    colnames(df)<-"col"
    n<-length(levels(df$col))
    name<-c(name,rep(var,n))
}
name <-name[-c(239,302)]
# On retire une de chaque a cause de modalite non presente dans train (ps_calc_06 et ps_calc_11)
coord<-cbind.data.frame(name,coord) 

modalite<-data.frame("modalite"=rownames(coord), stringsAsFactors = FALSE) %>%
    mutate(nb=str_count(modalite, pattern = "\\."), clean = case_when(nb == 0 ~ gsub("X","",modalite),
                                                                    nb == 1 ~ str_extract(modalite, regex("(?<=X)[0-9]*")),
                                                                    nb == 2 ~ str_extract(modalite, regex("(?<=X)[0-9]*\\.[0-9]*"))))
coord<-cbind.data.frame(coord,"modalite"=modalite$clean)
coord$modalite<-as.character(coord$modalite)
coord$modalite[which(name=="ps_reg_01")]<-seq(0,0.9,0.1)
coord$modalite[which(name=="ps_reg_02")]<-seq(0,1.8,0.1)
for(var in liste_var_factor) {
df<- coord %>% filter(name==var) %>% select(-name)
print(gg_proj_ind(df,1,2) + geom_text_repel(aes(label=modalite)) +ggtitle(var))
}

```


## Tables croisées avec la target

```{r}
liste_var_factor = type_col[type_col == "factor"]
levels(data_sel$ps_calc_01) = c(0:9)
levels(data_sel$ps_calc_02) = c(0:9)
levels(data_sel$ps_calc_03) = c(0:9)
```

```{r}
for (var in names(liste_var_factor)[2:length(liste_var_factor)]){
    print(gg_contingence_freq(get("var")))
}
```





## Transformation des variables continues
