---
title: "Évaluation des modèles"
date: "Étape 7"
output:
  rmdformats::readthedown:
    highlight: kate
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
               prompt=FALSE,
               tidy=FALSE,
               comment=NA)
opts_knit$set(width=75)
```

## Packages et fonctions externes

```{r, message=F, warning=F}
source("./0_packages.R")

library(doMC)
registerDoMC(cores = 1)
```

## Importations

```{r}
load("./../data/bases_29features.RData")
load("./../output/none_lgb_info.RData") # performance du LGB
load("./../output/up_lgb_info.RData") # performance du LGB avec scale_pos_weight = 26

train_id = train$id
train_XY = train %>% select(-id)
train_X = train %>% select(-id, -target)
train_Y = train$target %>% as.numeric()
train_Y = train_Y - 1

test_id = test$id
test_X = test %>% select(-id, -target)
test_Y = test$target %>% as.numeric()
test_Y = test_Y - 1
```

## Zone de stockage

```{r}
# path_exportation = file.path("/media/psqrt/SquareX/SAVE_MODELS/save_2020")
# path_exportation = file.path("/media/psqrt/DATA/save_models_2020")
path_exportation = file.path("/home/psqrt/Téléchargements/000")
```

## Importation / Calcul de la performance (gini) de tous les modèles

```{r, eval = F}
df_score_modeles = data.frame("Method" = character(),
                              "Sampling" = character(),
                              "Train" = numeric(),
                              "Validation" = numeric(),
                              "Test" = numeric(),
                              stringsAsFactors = F)
donnees_modeles = list.files(path_exportation)
donnees_modeles = donnees_modeles[-grep("ada|kppv", donnees_modeles)]
for (rdata_file in donnees_modeles){
    print(rdata_file)
    modele = gsub(".RData", "", rdata_file)
    print(modele)
    load(file.path(path_exportation, rdata_file))
    df_score_modeles = df_score_modeles %>%
        bind_rows(caret_eval_gini(get(modele), train_X, test_X, train_Y, test_Y))
    rm(list = get("modele"))
}


```

```{r}
# save(df_score_modeles, file = "./../data/df_score_modeles.RData")
load("./../data/df_score_modeles.RData")
load("./../output/none_lgb_info.RData")
load("./../output/up_lgb_info.RData")
load("./../output/glm_stacking_model_info.RData")
load("./../output/combinaison_model_info.RData")
load(file.path(path_exportation, "none_ada_model_trick.RData")) # none_ada_best_gini
load(file.path(path_exportation, "smote_ada_model_trick.RData")) # smote_ada_best_gini
load(file.path(path_exportation, "down_ada_model_trick.RData")) # down_ada_best_gini 

ada_lignes_df = data.frame("Method" = c("ada", "ada", "ada"),
                           "Sampling" = c("none", "smote", "down"),
                           "Train" = rep(NA, 3),
                           "Validation" = c(none_ada_best_gini, smote_ada_best_gini, down_ada_best_gini),
                           "Test" = rep(NA, 3),
                           stringsAsFactors = F)

df_score_modeles = df_score_modeles %>% 
    bind_rows(none_lgb_info) %>% 
    bind_rows(up_lgb_info) %>% 
    bind_rows(ada_lignes_df) %>% 
    bind_rows(glm_stacking_model_info) %>% 
    bind_rows(combinaison_model_info)
```

```{r}
df_score_modeles %>% 
    # filter(Method != "rpart2") %>%
    # filter(Method != "svmRadial") %>%
    filter(Validation > 0.23) %>% 
    ggplot() +
    aes(x = Sampling, y = Validation, group = Sampling, label = Method) +
    geom_hline(yintercept = 0.2721429, color = "red", linetype = 2) +
    stat_boxplot(geom = "errorbar", aes(color = Sampling)) +
    geom_boxplot(aes(color = Sampling)) +
    # geom_point(aes(color = Method)) +
    geom_point() +
    # geom_line(aes(group = Method, color = Method)) +
    geom_text_repel(direction = "x", nudge_x = -0.25) +
    coord_flip() +
    ylim(c(0.24, 0.29)) +
    xlab("Sampling Strategy") +
    ylab("Normalized Gini Coefficient (5 folds CV)") +
    annotation_custom(grob = textGrob(label = "LGBM benchmark", 
                                      gp = gpar(fontsize = 9, col = "red")), 
                      xmin = -3.5, 
                      ymin = 0.262) +
    theme_bw() +
    theme(legend.position = "none") +
    ggtitle(label = "Comparaison des performances (validation croisée 5 blocs)", 
            subtitle = "6 Modèles ont été retirés avant le construction des boxplots car trop mauvais \nglm_stack = stacking de XGB et LGB avec un GLM /// combi = 0.1 * pred_LGB + 0.9 * pred_XGB")
```

## Modèle retenu

Le modèle retenu est le combiné. Le gini associé à l'échantillon test est :

```{r}
cat("Coefficient Normalisé de Gini sur l'échantillon test :\n", df_score_modeles$Test[which(df_score_modeles$Method == "combi")])
```

